### ISSUE TITLE
Imagick extension stopped working

### ISSUE THREAD

**Issue by chekalsky** [brefphp/extra-php-extensions#104]
Couple of days ago imagick extension I've used stopped working. I thought it was connected to #99 but apparently it's not.

I've made very simple bref app to demonstrate it.
https://github.com/chekalsky/bref-imagick-issue

<img width="686" alt="image" src="https://user-images.githubusercontent.com/241584/100290443-a4f5ff00-2f7b-11eb-8aad-ab3eccc45678.png">

Error:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/bref-extra/imagick.so' (tried: /opt/bref-extra/imagick.so (libgomp.so.1: cannot open shared object file: No such file or directory), /opt/bref/lib/php/extensions/no-debug-non-zts-20190902//opt/bref-extra/imagick.so.so (/opt/bref/lib/php/extensions/no-debug-non-zts-20190902//opt/bref-extra/imagick.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

**Comment by danniehansen** [comment]
Not sure if it's related. Also experiencing exactly the same with GD after upgrading to Bref 1.0 and added GD layer / ini.

**Comment by jenschude** [comment]
https://github.com/brefphp/bref/blob/master/runtime/layers/tests.php

**Comment by jenschude** [comment]
Btw there was once a test added to bref itself if extensions are loadable. This could help and prevent such issues in the future. ;)

See https://github.com/brefphp/bref/blob/master/runtime/layers/tests.php

**Comment by hvipana** [comment]
> Not sure if it's related. Also experiencing exactly the same with GD after upgrading to Bref 1.0 and added GD layer / ini.

```
PHP Warning:  PHP Startup: gmp: Unable to initialize module
Module compiled with build ID=API20190902,TS
PHP    compiled with build ID=API20190902,NTS
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/bref-extra/gd.so' (tried: /opt/bref-extra/gd.so (libpng12.so.0: cannot open shared object file: No such file or directory), /opt/bref/lib/php/extensions/no-debug-non-zts-20190902//opt/bref-extra/gd.so.so (/opt/bref/lib/php/extensions/no-debug-non-zts-20190902//opt/bref-extra/gd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

**Comment by chekalsky** [comment]
+ #109

**Comment by Nyholm** [comment]
@chekalsky Are you using Bref 1.0?

If so, all the issues should be solved in 0.6.4 (will be released today)

**Comment by chekalsky** [comment]
@Nyholm yes, thank you!

**Comment by gocebo** [comment]
Just updated to 0.6.4 + bref 1.0.0 and still getting ` PHP Startup: Unable to load dynamic library '/opt/bref-extra/imagick.so'`

**Comment by Nyholm** [comment]
Thank you. Do you get any other error output?

**Comment by gocebo** [comment]
The same one as @chekalsky 
```PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/bref-extra/imagick.so' (tried: /opt/bref-extra/imagick.so (libgomp.so.1: cannot open shared object file: No such file or directory), /opt/bref/lib/php/extensions/no-debug-non-zts-20190902//opt/bref-extra/imagick.so.so (/opt/bref/lib/php/extensions/no-debug-non-zts-20190902//opt/bref-extra/imagick.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0```

**Comment by Nyholm** [comment]
I've done some work in https://github.com/brefphp/extra-php-extensions/pull/111. I test run all extensions, I found issues in GD but I cannot reproduce for the Imagick extension. 

Hm...

**Comment by hvipana** [comment]
I have updated to 0.6.4 and gd is still not working.

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/bref-extra/gd.so' (tried: /opt/bref-extra/gd.so (libpng15.so.15: cannot open shared object file: No such file or directory), /opt/bref/lib/php/extensions/no-debug-non-zts-20190902//opt/bref-extra/gd.so.so (/opt/bref/lib/php/extensions/no-debug-non-zts-20190902//opt/bref-extra/gd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

![image](https://user-images.githubusercontent.com/55196856/100419759-6fd5d380-3085-11eb-8890-dc4d49b2472c.png)

**Comment by Nyholm** [comment]
Thank you @hvipana 

I added some work and tests to this last night. We are not making sure that the extension is loaded properly. See #111. 
I am currently preparing a new release. 

What I find interesting is that some layers reported issues. But imagick isn't one of them... however, GD is fixed and gmp is fixed in 0.6.4 according to #109

**Comment by Nyholm** [comment]
I've just released 0.7.0: https://github.com/brefphp/extra-php-extensions/releases/tag/0.7.0

The test repo that @chekalsky works. Here is a PR: 
https://github.com/chekalsky/bref-imagick-issue/pull/1


Note that you no longer have to add: `extension=/opt/bref-extra/imagick.so`

**Comment by chekalsky** [comment]
@Nyholm Thank you, imagick is working now, but for some reason there is no support of PNG and JPG:

<img width="963" alt="image" src="https://user-images.githubusercontent.com/241584/100439595-05805b80-30a4-11eb-9b9d-dc3b9ed509df.png">

Updated https://github.com/chekalsky/bref-imagick-issue so you can check. Do you want me to create a new issue about it?

**Comment by Nyholm** [comment]
Thank you

**Comment by Nyholm** [comment]
Could you update this test file: https://github.com/brefphp/extra-php-extensions/blob/master/layers/imagick/test.php?

I want it to make sure that imagick is installed properly. You dont need to fix the docker image, just write some PHP that checks if `png` and `jpg` is supported. 

`layer=imagick php_versions=74 make test`

**Comment by chekalsky** [comment]
@Nyholm yep, https://github.com/brefphp/extra-php-extensions/runs/1463539675?check_suite_focus=true

**Comment by Nyholm** [comment]
Tests are added, @chekalsky updated the image to support png and jpg, and I've just tagged 0.7.1. 

Everything should be working now and never ever fail again thanks to the tests =)

**Comment by chekalsky** [comment]
Everything works fine!

<img width="188" alt="image" src="https://user-images.githubusercontent.com/241584/100476069-f241b000-30e4-11eb-8861-f5a5fd2ba093.png">
